#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: sql-dump-pv
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 1Gi
#  hostPath:
#    path: /home/ubuntu/kube-caso_3_cloud_native-metabase/resources
#  storageClassName: longhorn-storageclass 
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-dump-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

